name: Build Rust

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        config: [ debug, release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        name: Rust Cache
        with:
          prefix-key: ${{ hashFiles('**/Cargo.lock') }}-rust-${{ matrix.config }}
      - name: Build
        run: cargo ${{ matrix.config == 'release' && 'build --release' || 'build' }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.config }}-artifacts
          path: target/${{ matrix.config }}/mk-meili-mgn${{ matrix.os == 'windows-latest' && '.exe' || '' }}
